### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by Chad0XC0D3**
This has my nav bar. For future updates to the nav bar I plan to connect it to the other pages.

### CODE REVIEW

**Comment by robertsmelanie** [comment]
No conflicts

**Review by robertsmelanie — APPROVED** [review]
First Approval attempt

**Review by Jamflynt — APPROVED** [review]
So its asking for my approval to continue. I am approving but not looking at the code to remain an impartial 3rd party.

**Review by KellyeRichards — APPROVED** [review]
Let me know if this works. I'm doing it from my phone

**Pull request merged**
