### PR TITLE
Request to update main with education folder which includes the index

### PR DESCRIPTION
**Pull request by robertsmelanie**
Testing

### CODE REVIEW

**Comment by robertsmelanie** [comment]
Jamie said to send a pull request before I tried to merge

**Comment by Chad0XC0D3** [comment]
That’s fine with me

**Review by Chad0XC0D3 — APPROVED** [review]
It looks great!

**Review by KellyeRichards — APPROVED** [review]
I don't know what I'm doing lol

**Comment by robertsmelanie** [comment]
Merge

**Pull request merged**
